### ISSUE TITLE
Error 500 en MercadoPago - WooCommerce

### ISSUE THREAD

**Issue by sergiobrusisi** [mercadopago/cart-woocommerce#154]
Al activar el plugin,  cada 2 x 3 (no en todo momento) el admin me tira error 500

Alguien me podria indicar como solucionarlo? tengo un servidor dedicado en DONWEB  si hay algo que habilitar o poner por favor explicarmelo detalladamente ya que soy nuevo en esto.

Muchas Gracais

+copio el error

Fatal error: Uncaught exception 'MercadoPagoException' with message 'Failed to connect to api.mercadopago.com port 443: Connection timed out' in /home/aabqhwej/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php:885 Stack trace: #0 /home/aabqhwej/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php(983): MPRestClient::exec(Array, '3.0.15') #1 /home/aabqhwej/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(534): MPRestClient::get(Array, '3.0.15') #2 /home/aabqhwej/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(131): WC_Woo_Mercado_Pago_Module::get_categories() #3 /home/aabqhwej/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(123): WC_Woo_Mercado_Pago_Module->__construct() #4 [internal function]: WC_Woo_Mercado_Pago_Module::init_mercado_pago_class('') #5 /home/aabqhwej/public_html/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array) in /home/aabqhwej/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php on line 885

**Comment by alannewell** [comment]
Quizas no tiene nada que ver pero tuve un error similar y lo solucione poniendo la direccion de la tienda. Tenia habilitado lo de MercadoEnvios y calculo que utiliza es ainfo.

**Comment by luchiolb** [comment]
En este momento me esta sucediendo este error (de la nada). Parece ser una llamada a la API de MercadoPago que da TimeOut y por eso da Fatal Error el PHP al no manejar la excepción. 

Este es el detalle del error_log del Apache:

PHP Fatal error:  Uncaught exception 'MercadoPagoException' with message 'TCP connection reset by peer' in /wpfiles/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php:885\nStack trace:\n#0 /wpfiles/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php(983): MPRestClient::exec(Array, '3.0.15')\n#1 /wpfiles/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(534): MPRestClient::get(Array, '3.0.15')\n#2 /wpfiles/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(131): WC_Woo_Mercado_Pago_Module::get_categories()\n#3 /wpfiles/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(123): WC_Woo_Mercado_Pago_Module->__construct()\n#4 [internal function]: WC_Woo_Mercado_Pago_Module::init_mercado_pago_class('')\n#5 /wpfiles/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)\n#6 /wpfiles/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)\n#7 /wpfiles/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#8 in /wpfiles/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php on line 885

**Comment by nattsdaff** [comment]
Hola, alguno pudo resolverlo? Tengo el mismo problema, lado backend es imposible

**Comment by sergiobrusisi** [comment]
Me fui de donweb.
ese era mi gran probleam jaj
