### ISSUE TITLE
Grave Falla del Plugin

### ISSUE THREAD

**Issue by monpac** [mercadopago/cart-woocommerce#163]
El Plugin se ejecuta en toda la página y cuando api.mercadopago.com está caida o anda lento, retrasa toda la web o directamente no funciona la web. Paso screenshot del consumo del plugin dentro de una web nuestra visto por New Relic 
![consumo mp](https://user-images.githubusercontent.com/3440737/41175577-e951857a-6b33-11e8-9701-068b9c641607.png)

Espero que puedan verlo, pero con cualquier sistema de reporte de consumo debería de poder analizarse. Saludos

**Comment by luchiolb** [comment]
Exacto. Me esta pasando lo mismo. Fatal Error de Apache por una API caída de MercadoPago:

PHP Fatal error:  Uncaught exception 'MercadoPagoException' with message 'TCP connection reset by peer' in /wpfiles/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php:885\nStack trace:\n#0 /wpfiles/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php(983): MPRestClient::exec(Array, '3.0.15')\n#1 /wpfiles/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(534): MPRestClient::get(Array, '3.0.15')\n#2 /wpfiles/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(131): WC_Woo_Mercado_Pago_Module::get_categories()\n#3 /wpfiles/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(123): WC_Woo_Mercado_Pago_Module->__construct()\n#4 [internal function]: WC_Woo_Mercado_Pago_Module::init_mercado_pago_class('')\n#5 /wpfiles/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)\n#6 /wpfiles/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)\n#7 /wpfiles/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#8 in /wpfiles/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php on line 885

**Comment by monpac** [comment]
@luchiolb Mil gracias! estaba buscando el error de donde venía el consumo y ahora que mostrás el error (a nosotros no nos llegaba nunca a un fatal error), parece ser la función `get_categories()` la que hace el llamado en cualquier web que cargues de WordPress y alenta todo. Voy a ver de aplicar un parche rápido para solucionarlo. Saludos

**Comment by maximilianolc** [comment]
@monpac Buen día. Consulta, con que sacaste las estadísticas de los tiempos? Consulto por el screen que adjuntaste. Gracias.

**Comment by monpac** [comment]
@maximilianolc Es New Relic

**Comment by luchiolb** [comment]
Perfecto @monpac. Van a sacar una nueva versión con el fix?

**Comment by monpac** [comment]
@luchiolb hablo por nuestra compañía, pero probablemente si MP no ofrece respuesta vamos a publicar la modificación como un branch en nuestro repo y hacer el pull para que lo revisen.

**Comment by eduenriquez** [comment]
@monpac como traqueas el consumo del plugin de mercado pago en new relic?

**Comment by monpac** [comment]
@eduenriquez https://newrelic.com/products/application-monitoring

**Comment by dieguason** [comment]
Y? Finalmente lo resolvieron? Sigo con el Plugin desactivado por eso.

**Comment by monpac** [comment]
@dieguason si está resuelto, la solución es la que describí arriba.

**Comment by yacoalioi** [comment]
@monpac tenés pensado todavía subir un branch en su repo? Ya que MP no dio novedades.

**Comment by monpac** [comment]
@yacoalioi no es mío, es de la empresa. Pero si, la idea seríá subirlo cuando se apruebe.

**Comment by nattsdaff** [comment]
@monpac buenas, tengo el mismísimo problema, vos tenés a mano una solución? mil gracias!
