### ISSUE TITLE
Fatal error while activating plugin

### ISSUE THREAD

**Issue by GabrielQSchicora** [mercadopago/cart-woocommerce#178]
When I try to activate the plugin, a fatal error is generated:

Parse error: syntax error, unexpected T_FUNCTION in /home/persiana/public_html/loja/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php on line 910

And the plugin is not activated.

**Comment by xstocler** [comment]
I tried to download the plugin directly through wordpress.

**Comment by GabrielQSchicora** [comment]
Downloading directly through wordpress or by github, the problem continues

**Comment by xstocler** [comment]
Other plugins can you activate normally?

**Comment by GabrielQSchicora** [comment]
Yes, the only problem plugin is this

**Comment by paolagodoy** [comment]
Hello my web was pretty good (5 sales) 
I´ve downloaded the plugin directly through wordpress.
I´ve configurated, and prove it, everything was ok.
then... I´ve got this error....
Fatal error: Uncaught MercadoPagoException: Could not resolve host: api.mercadopago.com in /home/essocial/public_html/clientes/tienda/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php:848 Stack trace: #0 /home/essocial/public_html/clientes/tienda/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php(946): MPRestClient::exec(Array, '3.0.17') #1 /home/essocial/public_html/clientes/tienda/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(536): MPRestClient::get(Array, '3.0.17') #2 /home/essocial/public_html/clientes/tienda/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(131): WC_Woo_Mercado_Pago_Module::get_categories() #3 /home/essocial/public_html/clientes/tienda/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(123): WC_Woo_Mercado_Pago_Module->__construct() #4 /home/essocial/public_html/clientes/tienda/wp-includes/class-wp-hook.php(286): WC_Woo_Mercado_Pago_Module::init_mercado_pago_class('') #5 /home/essocial in /home/essocial/public_html/clientes/tienda/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php on line 848

Versión de WooCommerce; Versión 3.4.4 |
Vesión de Worpress: Versión 4.9.8
Versión de PHP: Versión Actual de PHP:  7.0
Versión del módulo, si está utilizando: Versión 3.0.17 

If I rename the name of the folder woocommerce-mercadopago my web works perfect.
¿What happend?
