### ISSUE TITLE
SSL connect error in 

### ISSUE THREAD

**Issue by cristianFryla** [mercadopago/cart-woocommerce#182]
Luego de la última actualización del plugin cada vez que intento activar el sitio me tira error 500. Hace poco que le pusimos SSL. La línea 848 que indica el error es el throw de lo siguiente:
$connect = self::build_request( $request, $version );
$api_result = curl_exec( $connect );

```
PHP Fatal error:  Uncaught MercadoPagoException: SSL connect error in /home/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php:848
Stack trace:
#0 /home/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php(946): MPRestClient::exec(Array, '3.0.17')
#1 /home/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(536): MPRestClient::get(Array, '3.0.17')
#2 /home/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(131): WC_Woo_Mercado_Pago_Module::get_categories()
#3 /home/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(123): WC_Woo_Mercado_Pago_Module->__construct()
#4 /home/public_html/wp-includes/class-wp-hook.php(286): WC_Woo_Mercado_Pago_Module::init_mercado_pago_class('')
#5 /home/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(Object(FusionCore_Plugin), Array)
#6 /home/public_html/wp in /home/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php on line 848
```

Alguien tiene un problema similar? Estuve viendo en otros issues que una persona tuvo el mismo problema con un servidor DonWeb, y mi sitio es un Cloud Server del mismo proveedor.

**Comment by cristianFryla** [comment]
Finalmente pude solucionarlo hablando con el ISP, modificaron la versión de PHP instalada y comenzó a funcionar sin problema. Si tienen un problema similar, hablen con el proveedor y chequen versión de PHP y de cURL instalada.
