### ISSUE TITLE
Los pagos siempre entran en modo "PENDIENTE DE PAGO"

### ISSUE THREAD

**Issue by sangreal89** [mercadopago/cart-woocommerce#190]
Hola estimad@s. Hace como 1 mes que estoy teniendo un problema con MercadoPago y WooCommerce.
Los pagos siempre entran en modo Pendiente de Pago, por mas que el pago se haya efectuado 100%.
Ya probé con diferentes plantillas, versiones de MercadoPago y WooCommerce y nada funciona. En el log de registro de errores me aparece este error:

2018-10-01T11:29:00+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Woo_Mercado_Pago_Module::utf8_ansi() in /home/ruhdesod/public_html/wp-content/plugins/woocommerce-mercadopago/includes/WC_WooMercadoPago_BasicGateway.php:1484
Stack trace:
#0 /home/ruhdesod/public_html/wp-content/plugins/woocommerce-mercadopago/includes/WC_WooMercadoPago_BasicGateway.php(1361): WC_WooMercadoPago_BasicGateway->check_mercado_envios(Array)
#1 /home/ruhdesod/public_html/wp-includes/class-wp-hook.php(286): WC_WooMercadoPago_BasicGateway->successful_request(Array)
#2 /home/ruhdesod/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /home/ruhdesod/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /home/ruhdesod/public_html/wp-content/plugins/woocommerce-mercadopago/includes/WC_WooMercadoPago_BasicGateway.php(1128): do_action('valid_mercadopa...', Array)
#5 /home/ruhdesod/public_html/wp-includes/class-wp-hook.php(286): WC_WooMercadoPago_BasicGateway->check_ipn_response('')
#6 /home/ruhdesod/public_html/w

¿Me pueden dar un idea de cual puede ser el error?
Muchas Gracias.

**Comment by jpmelnik** [comment]
@sangreal89 ¿Estás utilizando Cloudflare?

**Comment by grijos** [comment]
> @sangreal89 ¿Estás utilizando Cloudflare?

Hola. Yo tengo el mismo problema en dos sitios distintos. Uno usa Cloudflare y el otro no. ¿Vos pudiste solucionarlo?

**Comment by jpmelnik** [comment]
@sangreal89 

Por ahora lo he solucionado: En la sección "Firewall" del dominio correspondiente, ir a "Web Application Firewall" y **desactivar** "Browser Integrity Check".

**Comment by mateuszgwozdz** [comment]
same problem here

**Comment by jpmelnik** [comment]
¿Tienen instalado iThemes Security? o algun Plugin que hace cambios en URLs largas?

Do you have iThemes Security installed? or some Plugin that makes changes in long URLs?
