### ISSUE TITLE
Problem connecting to api.mercadopago.com

### ISSUE THREAD

**Issue by MarceloPedra** [mercadopago/cart-woocommerce#208]
Buen día gente. Esta semana vengo viendo problemas con la API de MercadoPago en sitios WordPress con WooCommerce. Desde hace un par de días me están dando error varios sitios que usan tanto el plugin oficial v3.0.x como el viejo plugin v2.2.x.

En todos los casos estuve debuggeando hasta que encontré que el problema se da en tiendas que usen SSL, y es independiente de la versión de cualquiera de los dos plugins, o de la versión de PHP/MySQL o de si usa Cloudflare o no.

El problema es que la conexion por curl a api.mercadopago.com da un timeout y como el plugin testea esa conexión en la pantalla de checkout, simplemente te da un error 500 que impide completar la compra. El error es aleatorio, por momentos anda y por momentos no, pero tengo logs de errores de PHP de hasta 1 GB de peso en tiendas grandes, y sitios chiquitos que dan error 500 en todo el frontend.

El problema podría ser de uptime de la API de MP, pero la solución que encontré fue desactivar el SSL, porque el error se da solo en sitios HTTPS. Si lo convertís a HTTP, funciona sin problemas. Así que puede ser un tema de certificados, o cacert. Yo en todos los servidores tengo TLS 1.2 tal como piden la especificaciones de MercadoPago :)

Alguna idea para solucionarlo que puedan actualizar ustedes en el plugin? O quizás es un problema en el el servidor de la API?

El error de PHP para que vean, es siempre el mismo en todos los sitios:

[22-Sep-2018 20:34:07 UTC] PHP Fatal error: Uncaught MercadoPagoException: Could not resolve host: api.mercadopago.com in /home/nombresitio/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php:848
Stack trace:
#0 /home/nombresitio/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php(946): MPRestClient::exec(Array, '3.0.17')
#1 /home/nombresitio/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(536): MPRestClient::get(Array, '3.0.17')
#2 /home/nombresitio/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(131): WC_Woo_Mercado_Pago_Module::get_categories()
#3 /home/nombresitio/public_html/wp-content/plugins/woocommerce-mercadopago/woocommerce-mercadopago.php(123): WC_Woo_Mercado_Pago_Module->__construct()
#4 /home/nombresitio/public_html/wp-includes/class-wp-hook.php(286): WC_Woo_Mercado_Pago_Module::init_mercado_pago_class('')
#5 /home/nombresitio/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/nombresitio/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /home/nombresitio/public_html/wp-settings.php(327): do_action('plugins_loaded')
#8 /home/nombresitio/public_html/wp-config.php(77): require_once('/home/agenciasl...')
#9 /home/nombresitio/public_html/wp-load.php(37): require_once('/home/agenciasl...')
#10 /home/nombresitio/public_html/wp-cron.php(33): require_once('/home/agenciasl...')
#11 {main}
thrown in /home/nombresitio/public_html/wp-content/plugins/woocommerce-mercadopago/includes/sdk/lib/mercadopago.php on line 848

Espero puedan verlo pronto. 
Gracias!

**Comment by mvconline1** [comment]
Experimentando lo mismo. En mi caso, aparte de error 500 aleatoriamente, también tardaba hasta 40 segs para abrir pedidos individuales. Se solucionó quitando el SSL.

**Comment by Lolosan** [comment]
> 
> 
> Experimentando lo mismo. En mi caso, aparte de error 500 aleatoriamente, también tardaba hasta 40 segs para abrir pedidos individuales. Se solucionó quitando el SSL.

El SSL lo desactivaste en el sitio entero (quedó solo http, sin https) o tocaste el código para que solo sea en esa llamada?
