### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_order_number() on boolean in /wp-content/plugins/woo-mercado-pago-module/includes/class-wc-product-mp_recurrent.php:21 when trying to create a new product

### ISSUE THREAD

**Issue by jrpa** [mercadopago/cart-woocommerce#89]
Hello!

I recently started using v3.0 and found this fatal error everytime I try to create a new product in WooCommerce:

Fatal error: Uncaught Error: Call to a member function get_order_number() on boolean in /.../wp-content/plugins/woo-mercado-pago-module/includes/class-wc-product-mp_recurrent.php:21

Stack trace:
#0 /.../wp-includes/class-wp-hook.php(300): add_meta_boxes('product')
#1 /.../wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /.../wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /.../wp-admin/edit-form-advanced.php(323): do_action('add_meta_boxes', 'product', Object(WP_Post))
#4 /.../wp-admin/post-new.php(85): include('/homepages/18/d...')
#5 {main} thrown in **/homepages/18/d678135194/htdocs/mishibot/wp-content/plugins/woo-mercado-pago-module/includes/class-wc-product-mp_recurrent.php** on line **21**

**Comment by thamaraiselvam** [comment]
I also get the same error  Did you fix it?
